[fix]: failed links

diff --git a/cmphash b/cmphash
--- a/cmphash
+++ b/cmphash
@@ -1,1 +1,79 @@
-../bash-scripts/cmphash
+#!/bin/bash
+
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+BLUE='\033[0;35m'
+NC='\033[0m'
+
+script_name="$(basename "${0}")"
+sums=($(awk '{ i=split($0,x,"/"); print x[i] }' <<<"$(find /usr/bin/ -name '*sum')"))
+usage="usage: ${script_name} [-m algorithm] [FILE] [HASH]"
+
+while getopts "m:" opt; do
+  case $opt in
+  m)
+    norm="\<${OPTARG}\>"
+    norm_sum="\<${OPTARG}sum\>"
+    method=""
+
+    for sum in "${sums[@]}"; do
+      if [[ "${sum}" == "${OPTARG}" || "${sum}" == "${OPTARG}sum" ]]; then
+        method="${sum}"
+        break
+      fi
+    done
+
+    if [[ -z "${method}" ]]; then
+      echo "${script_name}: invalid argument '${OPTARG}' for '-m'"
+      echo "valid arguments are: ${sums[*]}"
+      exit 1
+    fi
+    ;;
+  \?)
+    exit 1
+    ;;
+  esac
+done
+
+if [ -z "${method+x}" ]; then
+  echo "${script_name}: Argument -m is mandatory"
+  echo "${usage}"
+  exit 1
+fi
+
+shift $((OPTIND - 1))
+
+if [[ -z ${1} || -z ${2} ]]; then
+  echo "Missing operand"
+  echo "${usage}"
+  exit 1
+fi
+
+if [[ ${#} -gt 2 ]]; then
+  echo "To many operands"
+  echo "${usage}"
+  exit 1
+fi
+
+file="${1}"
+test="${2}"
+
+if [[ ! -e "${file}" ]]; then
+  echo "${script_name}: ${file} - no such file or directory"
+  exit -1
+fi
+
+if [[ -d "${file}" ]]; then
+  echo "${script_name}: ${file} - is a directory"
+  exit -1
+fi
+
+hash="$(${method} ${file} | cut -d' ' -f1)"
+
+if [[ "${hash}" == "${test}" ]]; then
+  echo -e "${GREEN}MATCH${NC}"
+else
+  echo -e "${RED}FAIL${NC}"
+  echo "FILE    :  ${hash}"
+  echo "ORIGINAL:  ${test}"
+fi
diff --git a/link b/link
--- a/link
+++ b/link
@@ -1,1 +1,48 @@
-../bash-scripts/link
+#!/bin/bash
+
+set -euo pipefail
+
+bin_path="${HOME}/bin"
+SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
+SCRIPT_PATH="${SCRIPT_DIR}/$(basename $BASH_SOURCE)"
+
+if [[ -L ${bin_path} ]]; then
+  echo "${bin_path} is symlink"
+  while true; do
+    read -rp "Should it be replaced? (y/n)" yn
+    case $yn in
+    [Yy])
+      rm "${bin_path}"
+      break
+      ;;
+    [Nn]) exit 0 ;;
+    *) echo "invalid input" ;;
+    esac
+  done
+fi
+
+if [[ ! -e "${bin_path}" ]]; then
+  mkdir "${bin_path}"
+elif [[ ! -d "${bin_path}" && ! -L "${bin_path}" ]]; then
+  echo "${bin_path} not directory or symlink!"
+  exit -1
+fi
+
+for script in "${SCRIPT_DIR}"/*; do
+  if [[ ! $(head -n 1 "${script}") == "#!/bin/bash" ]]; then
+    continue
+  fi
+  if [[ $script -ef $SCRIPT_PATH ]]; then
+    continue
+  fi
+  if [[ -L "${bin_path}/$(basename $script)" ]]; then
+    continue
+  fi
+  ln -s "${script}" "${bin_path}/$(basename $script)"
+done
+
+envfile="${SCRIPT_DIR}/.env.sample"
+
+if [[ ! -e "${envfile}" ]]; then
+  cp "${envfile}" "${bin_path}"
+fi
diff --git a/up b/up
--- a/up
+++ b/up
@@ -1,1 +1,71 @@
-../bash-scripts/up
+#!/bin/bash
+
+# Colors
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m'
+
+trap '
+  trap - INT
+  kill -s INT "$$"
+  exit
+' INT
+
+if ! command -v sudo &>/dev/null; then
+  echo -e "${RED}ERROR: sudo is not available. install it to run this script.${NC}"
+  exit 1
+fi
+
+# apt update cycle
+echo -e "${GREEN}APT update${NC}"
+sudo bash -c 'apt update && apt upgrade && apt autoremove && apt clean'
+
+# flatpak
+if command -v flatpak 2>&1 >/dev/null; then
+  echo -e "${GREEN}flatpak update and cleanup${NC}"
+  flatpak update
+  flatpak uninstall --unused
+fi
+
+# homebrew
+if command -v brew 2>&1 >/dev/null; then
+  echo -e "${GREEN}homebrew${NC}"
+  brew update
+  brew upgrade
+  brew autoremove
+fi
+
+# asdf
+if command -v asdf 2>&1 >/dev/null; then
+  echo -e "${GREEN}updateing asdf and plugins${NC}"
+  asdf update && asdf plugin update --all
+fi
+
+# atuin
+if command -v atuin-update 2>&1 >/dev/null; then
+  echo -e "${GREEN}updateing atuin${NC}"
+  atuin-update
+fi
+
+# Rust, rustup and cargo ceates
+if command -v cargo 2>&1 >/dev/null; then
+  if command -v rustup 2>&1 >/dev/null; then
+    echo -e "${GREEN}updateing rust & rustup${NC}"
+    rustup update
+  else
+    echo -e "${RED}WARNING: cargo installed but no rustup${NC}"
+  fi
+  if command -v cargo-updater 2>&1 >/dev/null; then
+    echo -e "${GREEN}updateing cargo creates${NC}"
+    cargo updater -u
+  elif [[ $(cargo install --list) == *"cargo-install-update"* ]]; then
+    echo -e "${GREEN}updateing cargo creates${NC}"
+    cargo install-update -a
+  fi
+fi
+
+# platformio
+if command -v platformio 2>&1 >/dev/null; then
+  echo -e "${GREEN}updateing platformIO${NC}"
+  platformio upgrade
+fi
